#
# Gradle optimizations
#
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m

#
# Java environment
#
env.maven.group=dev.buildit
env.java.version=25

#
# Mod information
#
project.group=Buildit
project.name=Create
project.description=[UNOFFICIAL] Aesthetic Solarpunk Technology powered by Steam
project.website=https://adaliszk.github.io/gradle-buildit-indev
project.version=0.1.0
project.license=BSD-3-Clause

#
# Minecraft
#
minecraft.version=26.1

#
# Hytale
#
hytale.patchline=release
hytale.version=2026.1.17-4b0f30090
